#!/usr/bin/python3
def raise_exception():
    num = 12
    num2 = "str"
    num/num2
